spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:1234/appsmart-demo
    username: user
    password: user
  liquibase:
    change-log: classpath:db/master.xml
logging:
  level:
    ROOT: INFO
    com.appsmart.demo: DEBUG