version: '2'
services:
  postgres:
    image: postgres:14
    container_name: db
    ports:
      - 1234:5432
    environment:
      - POSTGRES_DB=appsmart-demo
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=user